INSERT INTO BLC_CATEGORY (CATEGORY_ID,DESCRIPTION,NAME,URL,ACTIVE_START_DATE) VALUES (2009,'Category for tools','Automobile','/automobile',CURRENT_TIMESTAMP);
INSERT INTO BLC_CATEGORY (CATEGORY_ID,DESCRIPTION,NAME,URL,ACTIVE_START_DATE) VALUES (2010,'Spanner sub cat for automobile','Spanner','/spanner',CURRENT_TIMESTAMP);


INSERT INTO BLC_CATEGORY_XREF (CATEGORY_XREF_ID, SUB_CATEGORY_ID, CATEGORY_ID, DISPLAY_ORDER, DEFAULT_REFERENCE) VALUES (100,2010,2009,-7.000000,TRUE);



INSERT INTO BLC_PRODUCT (PRODUCT_ID, URL, MANUFACTURE, IS_FEATURED_PRODUCT) VALUES (10000,'/spanner/product1','Sample products',TRUE);


INSERT INTO BLC_SKU (SKU_ID,DEFAULT_PRODUCT_ID,NAME,LONG_DESCRIPTION,RETAIL_PRICE,COST,TAXABLE_FLAG,DISCOUNTABLE_FLAG,ACTIVE_START_DATE, INVENTORY_TYPE) VALUES (10000,10000,'Spanner Product','Spanner used for various automobiles',10.99,3.89,'Y','Y',CURRENT_TIMESTAMP, 'CHECK_QUANTITY');


UPDATE BLC_PRODUCT SET DEFAULT_SKU_ID = 10000 WHERE PRODUCT_ID = 10000;


INSERT INTO BLC_CATEGORY_PRODUCT_XREF (CATEGORY_PRODUCT_ID, PRODUCT_ID, CATEGORY_ID, DISPLAY_ORDER, DEFAULT_REFERENCE) VALUES (10000,10000,2010,1,TRUE);

INSERT INTO BLC_MEDIA (MEDIA_ID, URL, TITLE, ALT_TEXT) VALUES (70001,'/cmsstatic/img/sauces/spanner.jpg','Spanner Image','primary');

INSERT INTO BLC_SKU_MEDIA_MAP (SKU_MEDIA_ID, BLC_SKU_SKU_ID, MEDIA_ID, MAP_KEY) VALUES (-2000,10000,70001,'primary');

INSERT INTO BLC_STATIC_ASSET (STATIC_ASSET_ID, MIME_TYPE, STORAGE_TYPE, FULL_URL, NAME) VALUES (70001,'image/jpg','FILESYSTEM','/img/sauces/spanner.jpg','Spanner Image');




